apiVersion: v1
kind: PersistentVolume
metadata:
  name: proxysql-0-pv
spec:
  storageClassName: proxysql-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kworker4.example.com