apiVersion: v1
kind: Service
metadata:
  name: proxysql-nodeport
spec:
  selector:
    app: proxysql
  type: NodePort
  ports:
  - name: mysql-np
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31555
  - name: proxyadm-np
    port: 6032
    protocol: TCP
    targetPort: 6032
    nodePort: 31577